version: '3'

networks:
    nginx-php74-mysql8-cicd:

services:
    
    # nginx
    nginx-service-cicd:
        image: nginx:stable-alpine
        container_name: nginx-container-cicd
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service-cicd
            - mysql8-service-cicd
        networks:
            - nginx-php74-mysql8-cicd

    # php
    php74-service-cicd:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container-cicd
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/project
        networks:
            - nginx-php74-mysql8-cicd

    # mysql
    # mysql8-service-cicd:
    #     image: mysql:8
    #     container_name: mysql8-container-cicd
    #     ports:
    #         - "4306:3306"
    #     volumes:
    #         - ./:/var/lib/mysql
    #     command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #     # restart: always # always restart unless stopped manually
    #     environment:
    #         MYSQL_USER: root
    #         MYSQL_ROOT_PASSWORD: secret
    #         MYSQL_PASSWORD: secret
    #     networks:
    #         - nginx-php74-mysql8-cicd

    # node
    # node-service:
    #     image: node:latest
    #     container_name: node-container
    #     volumes:
    #         - ./app:/var/www/project
    #     working_dir: /var/www/project
    #     networks:
    #         - nginx-php74-mysql8-cicd