<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXVUNadf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXVUNadf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXVUNadf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXVUNadf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXVUNadf\App_KernelDevDebugContainer([
    'container.build_hash' => 'XVUNadf',
    'container.build_id' => 'e3661e28',
    'container.build_time' => 1659361568,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXVUNadf');
